/*
* generated by Xtext
*/
package de.uni_marburg.splittr.description;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SplittingDescriptionStandaloneSetup extends SplittingDescriptionStandaloneSetupGenerated{

	public static void doSetup() {
		new SplittingDescriptionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

