/*
 * generated by Xtext
 */
package de.uni_marburg.splittr.description;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SplittingDescriptionRuntimeModule extends de.uni_marburg.splittr.description.AbstractSplittingDescriptionRuntimeModule {

}
