/*
 * generated by Xtext
 */
package de.uni_marburg.splittr.description.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SplittingDescriptionUiModule extends de.uni_marburg.splittr.description.ui.AbstractSplittingDescriptionUiModule {
	public SplittingDescriptionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
