/*
 * generated by Xtext
 */
package de.uni_marburg.splittr.description.ui.contentassist

import de.uni_marburg.splittr.description.ui.contentassist.AbstractSplittingDescriptionProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SplittingDescriptionProposalProvider extends AbstractSplittingDescriptionProposalProvider {
}
