/*
* generated by Xtext
*/
package de.uni_marburg.splittr.description.parser.antlr;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import de.uni_marburg.splittr.description.services.SplittingDescriptionGrammarAccess;

public class SplittingDescriptionParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SplittingDescriptionGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.uni_marburg.splittr.description.parser.antlr.internal.InternalSplittingDescriptionParser createParser(XtextTokenStream stream) {
		return new de.uni_marburg.splittr.description.parser.antlr.internal.InternalSplittingDescriptionParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SplittingDescription";
	}
	
	public SplittingDescriptionGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SplittingDescriptionGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
