/*
* generated by Xtext
*/
package de.uni_marburg.splittr.description.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SplittingDescriptionAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/uni_marburg/splittr/description/parser/antlr/internal/InternalSplittingDescription.tokens");
	}
}
