/*
 * generated by Xtext
 */
package de.uni_marburg.splittr.description.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.uni_marburg.splittr.description.ui.internal.SplittingDescriptionActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SplittingDescriptionExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SplittingDescriptionActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SplittingDescriptionActivator.getInstance().getInjector(SplittingDescriptionActivator.DE_UNI_MARBURG_SPLITTR_DESCRIPTION_SPLITTINGDESCRIPTION);
	}
	
}
